# Updated config.yml
# # Kind Cluster Configuration
# Creates 1 control-plane (master) node and 3 worker nodes
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubernetes

nodes:
  - role: control-plane
    image: kindest/node:v1.30.0
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
  
  - role: worker
    image: kindest/node:v1.30.0
  
  - role: worker
    image: kindest/node:v1.30.0
  
  - role: worker
    image: kindest/node:v1.30.0
